<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="31255" started-at="2020-01-09T01:57:46Z" finished-at="2020-01-09T01:58:17Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="31255" started-at="2020-01-09T01:57:46Z" finished-at="2020-01-09T01:58:17Z">
      <class name="com.training.sanity.tests.RTTC_001_Registerpage">
        <test-method status="PASS" signature="setUpBeforeClass()[pri:0, instance:com.training.sanity.tests.RTTC_001_Registerpage@4501b7af]" name="setUpBeforeClass" is-config="true" duration-ms="47" started-at="2020-01-09T01:57:46Z" finished-at="2020-01-09T01:57:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUpBeforeClass -->
        <test-method status="PASS" signature="setUp()[pri:0, instance:com.training.sanity.tests.RTTC_001_Registerpage@4501b7af]" name="setUp" is-config="true" duration-ms="16376" started-at="2020-01-09T01:57:46Z" finished-at="2020-01-09T01:58:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="FAIL" signature="Registration()[pri:0, instance:com.training.sanity.tests.RTTC_001_Registerpage@4501b7af]" name="Registration" duration-ms="12891" started-at="2020-01-09T01:58:02Z" finished-at="2020-01-09T01:58:15Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Congratulations! Your new account has been successfully created!] but found [An email with a confirmation link has been sent your email address.]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Congratulations! Your new account has been successfully created!] but found [An email with a confirmation link has been sent your email address.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.training.pom.RTTC_001_RegisterPOM.Registration(RTTC_001_RegisterPOM.java:98)
at com.training.sanity.tests.RTTC_001_Registerpage.Registration(RTTC_001_Registerpage.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Registration -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.training.sanity.tests.RTTC_001_Registerpage@4501b7af]" name="tearDown" is-config="true" duration-ms="1888" started-at="2020-01-09T01:58:15Z" finished-at="2020-01-09T01:58:17Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.training.sanity.tests.RTTC_001_Registerpage -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
